---
# Run `pre-commit install` at the root of the repository for the monorepo
#  `.pre-commit-config.yaml`
# (optionally) add more here for your use-case.
repos:
  # bandit -r --severity-level medium --confidence-level medium -f html -o bandit-report-${{ matrix.package }}.html -c "pyproject.toml" .
  # uv run --frozen pytest --cov --cov-branch --cov-report=term-missing
  # uv run --frozen pyright

  - repo: local
    hooks:
    - id: bandit
      name: bandit
      stages: [pre-commit, pre-push]
      pass_filenames: false
      always_run: true
      language: system
      entry: uv
      args:
        - --project
        - ./src/core-mcp-server
        - run
        - --frozen
        - bandit
        - -r
        - --severity-level
        - medium
        - --confidence-level
        - medium
        - -c
        - ./src/core-mcp-server/pyproject.toml
        - ./src/core-mcp-server

    - id: pyright
      name: pyright
      stages: [pre-commit, pre-push]
      pass_filenames: false
      always_run: true
      language: system
      entry: uv
      args:
        - --project
        - ./src/core-mcp-server
        - run
        - --frozen
        - pyright
        - --project
        - ./src/core-mcp-server

    - id: pytest
      name: pytest
      stages: [pre-commit, pre-push]
      pass_filenames: false
      always_run: true
      language: system
      entry: uv
      args:
        - --project
        - ./src/core-mcp-server
        - run
        - --frozen
        - pytest
        - --cov-branch
        - --cov-report=term-missing
        - ./src/core-mcp-server/tests
